package com.udacity.movietip.data.model;

import java.util.ArrayList;

// Generated by robopojogenerator
public class ReviewsIndexed{

	private ArrayList<Reviews> results;

	public ArrayList<Reviews> getResults(){
		return results;
	}

}