package com.udacity.movietip.data.model;

import java.util.ArrayList;

// Generated by robopojogenerator")
public class TrailersIndexed {

	private ArrayList<Trailers> results;

	public ArrayList<Trailers> getResults(){
		return results;
	}
}