package com.udacity.movietip.data.model;

import java.util.ArrayList;
import java.util.List;

// Generated by robopojogenerator")
public class TrailersIndexed {

	private int id;
	private ArrayList<Trailers> results;

	public void setId(int id){
		this.id = id;
	}

	public int getId(){
		return id;
	}

	public void setResults(ArrayList<Trailers> results){
		this.results = results;
	}

	public ArrayList<Trailers> getResults(){
		return results;
	}
}