package com.udacity.movietip.data.model;

import java.util.List;

// Generated by robopojogenerator")
public class TrailersIndexed {

	private int id;
	private List<Trailers> results;

	public void setId(int id){
		this.id = id;
	}

	public int getId(){
		return id;
	}

	public void setResults(List<Trailers> results){
		this.results = results;
	}

	public List<Trailers> getResults(){
		return results;
	}
}